### ISSUE TITLE
Multiple files are opened when only one is selected

### ISSUE THREAD

**Issue by notuntoward** [bdarcus/citar#416]
I like the new and more citation-specific minibuffer response that I see when I type `C-o` on a cite link.  However, if the bib entry has more than one file associated with it, and if I select only one of them, then all files are opened anyway.  

In the screenshot below, if hit the `Enter` key, all three pdfs will be opened by the external reader.

The other change I notice is that cite links are no longer highlighted.  But maybe that's due to some change in org itself?

![image](https://user-images.githubusercontent.com/3851891/142128555-07edab82-7c0d-4b5d-b6a6-a96b4dd4a740.png)

**Config**

```
(use-package citar
  :straight (:host github :repo "bdarcus/citar")
  :bind (("C-c b" . citar-insert-citation)
         ;; also  C-c C-x C-@
         (:map org-mode-map :package org ("C-c b" . #'org-cite-insert))
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset))
  :custom
  ;; https://github.com/bdarcus/citar/issues/407#issuecomment-968158550
  (org-cite-global-bibliography '("~/ref/energy.bib"
                                  "~/ref/DOE_brainstorm/deepSolarDOE.bib"))
  (citar-bibliography '("~/ref/energy.bib"
                        "~/ref/DOE_brainstorm/deepSolarDOE.bib"))
  (citar-library-paths '("~/ref/papers"
                         "~/ref/DOE_brainstorm/papers"))
  ;; so citar can open JabRef-style file fields
  (setq citar-file-parser-functions '(citar-file-parser-default
                                      citar-file-parser-triplet))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  (citar-at-point-function 'embark-act) ; So more C-o options than file list
  (citar-file-open-function 'citar-file-open-external)
  ;; (citar-open-note-function 'orb-citar-edit-note) ; default, I think
  ;; (citar-file-find-additional-files t) ; finds pdfs... w/ same start as key
  ;; (citar-open-note-function 'orb-bibtex-actions-edit-note') ; OR
  :init
  ;; if .bib file changes, "invalidate the cache by default".  Is that good?
  ;; https://github.com/bdarcus/citar#refreshing-the-library-display
  (citar-filenotify-setup '(LaTeX-mode-hook org-mode-hook))
  :config
  ;; this is supposed to pick up styles, like IEEE but doesn't
  ;; (setq org-cite-csl-styles-dir "~/Zotero/styles") ;; hangs org on startup
  )

;; use consult-completing-read for enhanced interface
;; From: https://github.com/bdarcus/citar
(with-eval-after-load 'embark
  (advice-add #'completing-read-multiple :override
              #'consult-completing-read-multiple))
```

**Comment by bdarcus** [comment]
> In the screenshot below, if hit the `Enter` key, all three pdfs will be opened by the external reader.
> 
> The other change I notice is that cite links are no longer highlighted. But maybe that's due to some change in org itself?

I can't reproduce that.

My guess is something went wrong with your install, and both of the above are outcome of that.

**Comment by bdarcus** [comment]
Actually, let's ping @localauthor to maybe get a second confirmation. I don't actually have mine setup to test the new extended search feature.

I still don't think it's possible given the code, but ...

**Comment by localauthor** [comment]
I think that should fix it. There was no "else" condition in the "if" statement at the end of citar-open-library-files, so it just blazed through and opened all files...

Also, it seems that the last commit needed ">" rather than "<." Does that seem right?

**Comment by bdarcus** [comment]
> I think that should fix it. 

Thanks! Merged.

Can you test the commit and confirm @notuntoward?

> Also, it seems that the last commit needed ">" rather than "<." Does that seem right?

It should only prompt to select a file if there are more than one result.

**Comment by notuntoward** [comment]
This does fix it.  If I select one file, it opens one file.

The lack of cite link face problem remains, though.  If I put the cursor on a `cite:` link and run `M-x describe-face`, the answer I get is `('default')` which is also what I see.  If I do the same for an `org-ref` link, the answer I get is `(default 'org-ref-cite-face')`, and that link is colored as normal.

**Comment by bdarcus** [comment]
> The lack of cite link face problem remains, though.

I don't know what to tell you about that. Fontification is handled by the oc-basic code.

I have in the past run into times where it doesn't work, for reasons I could never figure out.

But it works fine for me now.

I know @roshanshariff has seen similar recently.

**Comment by bdarcus** [comment]
> I don't know what to tell you about that. Fontification is handled by the oc-basic code.

Perhaps this post from today is relevant?

https://lists.gnu.org/archive/html/emacs-orgmode/2021-11/msg00408.html

Proposes to upgrade fontification in org generally.

**Comment by notuntoward** [comment]
It is!  Thanks.
